# Generated by Django 3.1.1 on 2020-09-14 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('second', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='reg_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='second.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='reg_user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='second.user'),
            preserve_default=False,
        ),
    ]
